# GitHub Actions 工作流示例
# 将此文件复制到 .github/workflows/distributed-tests.yml

name: Distributed Module Tests

on:
  push:
    paths:
      - 'lama_cleaner/distributed/**'
  pull_request:
    paths:
      - 'lama_cleaner/distributed/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, "3.10"]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        cd lama_cleaner/distributed
        make install-deps
    
    - name: Check dependencies
      run: |
        cd lama_cleaner/distributed
        make check-deps
    
    - name: Run tests
      run: |
        cd lama_cleaner/distributed
        make test-coverage
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        file: ./lama_cleaner/distributed/htmlcov/coverage.xml
        flags: distributed
        name: distributed-coverage